/*
 * 真实词条库（从抖音「随机喝酒大转盘 / 小决定App」视频逐帧抄录）
 * ------------------------------------------------------------------
 * 玩法：转到某条，符合「…的人」条件的人就喝。
 * 这些是从视频里一帧一帧扒下来的原汁原味词条，是整个词库的「种子」。
 *
 * 用 window.ENTRIES_DATA 挂到全局，方便 file:// 直接打开也能用（不走 fetch）。
 * 每条：{ text, category }
 *   category: 习惯 / 经历 / 才艺 / 爱好 / 其他
 */
window.ENTRIES_DATA = [
  // —— 习惯：日常生活习惯 ——
  { text: '每天必须吃甜点的人', category: '习惯' },
  { text: '每天喝两杯以上咖啡的人', category: '习惯' },
  { text: '早上经常睡到10点的人', category: '习惯' },
  { text: '经常忘记关房间灯的人', category: '习惯' },
  { text: '每周发朋友圈超过两次的人', category: '习惯' },
  { text: '一个月吃三次火锅的人', category: '习惯' },
  { text: '每周吃宵夜超过两次的人', category: '习惯' },
  { text: '每周吃一次烧烤的人', category: '习惯' },
  { text: '每天吃零食超过两次的人', category: '习惯' },
  { text: '每周点外卖超过三次的人', category: '习惯' },
  { text: '每天吃冰淇淋的人', category: '习惯' },
  { text: '日常穿拖鞋出门的人', category: '习惯' },
  { text: '熬夜看球赛的人', category: '习惯' },
  { text: 'KTV必点经典老歌的人', category: '习惯' },
  { text: '吃蛋糕从不留奶油的人', category: '习惯' },
  { text: '手机里自拍超过50张的人', category: '习惯' },

  // —— 经历：发生在你身上的事 ——
  { text: '今年被雨淋湿超过三次的人', category: '经历' },
  { text: '收到过交通罚单的人', category: '经历' },
  { text: '被催婚超过五次的人', category: '经历' },
  { text: '被父母唠叨学习或工作的人', category: '经历' },
  { text: '本周迟到过至少一次的人', category: '经历' },
  { text: '被电瓶车撞过的人', category: '经历' },
  { text: '被叫错名字超过十次的人', category: '经历' },
  { text: '被陌生人认错过的人', category: '经历' },
  { text: '被老师点名批评过的人', category: '经历' },
  { text: '被朋友吐槽过性格的人', category: '经历' },
  { text: '被虫子吓到尖叫过的人', category: '经历' },
  { text: '因吃醋和朋友吵架过的人', category: '经历' },
  { text: '借钱给朋友超过三次的人', category: '经历' },
  { text: '被朋友拉去当模特的人', category: '经历' },
  { text: '被认错性别过的人', category: '经历' },
  { text: '收到过奇怪礼物的人', category: '经历' },
  { text: '讲笑话没人笑过的人', category: '经历' },
  { text: '夏天晒黑两个色号的人', category: '经历' },
  { text: '夏天被蚊子咬过10次以上的人', category: '经历' },
  { text: '买东西砍价成功过的人', category: '经历' },

  // —— 才艺：能秀一手的技能 ——
  { text: '会用筷子夹豆子的人', category: '才艺' },
  { text: '会用三种字体写字的人', category: '才艺' },
  { text: '能讲一句人生哲理的人', category: '才艺' },
  { text: '能讲一件童年糗事的人', category: '才艺' },
  { text: '能模仿卡通人物声音的人', category: '才艺' },
  { text: '能说三种以上方言的人', category: '才艺' },
  { text: '会做三道以上拿手菜的人', category: '才艺' },
  { text: '能背一首古诗的人', category: '才艺' },
  { text: '能用外语说一段话的人', category: '才艺' },
  { text: '能模仿三种动物叫声的人', category: '才艺' },
  { text: '会跳任何一种街舞的人', category: '才艺' },
  { text: '能唱出高音C的人', category: '才艺' },
  { text: '能画一幅素描的人', category: '才艺' },
  { text: '能模仿某位名人讲话的人', category: '才艺' },
  { text: '会背至少三句土味情话的人', category: '才艺' },
  { text: '讲冷幽默让大家沉默的人', category: '才艺' },
  { text: '能吃完一整份麻辣火锅的人', category: '才艺' },
  { text: '跑步能坚持10公里的人', category: '才艺' },
  { text: '自制过表情包的人', category: '才艺' },

  // —— 爱好：兴趣与影音娱乐 ——
  { text: '看过至少五部恐怖片的人', category: '爱好' },
  { text: '看过十部科幻片的人', category: '爱好' },
  { text: '读过100本以上小说的人', category: '爱好' },
  { text: '每周追至少一档综艺的人', category: '爱好' },
  { text: '追过美食节目的人', category: '爱好' },
  { text: '追过三部悬疑剧的人', category: '爱好' },
  { text: '看过五部纪录片的人', category: '爱好' },
  { text: '玩过十种以上桌游的人', category: '爱好' },
  { text: '手机里有80年代歌曲的人', category: '爱好' },
  { text: '每周追一档真人秀的人', category: '爱好' },
  { text: '知道五个冷知识的人', category: '爱好' },
  { text: '相信星座决定命运的人', category: '爱好' },
  { text: '收藏过奇怪物品的人', category: '爱好' },
  { text: '最爱吃热带水果的人', category: '爱好' },

  // —— 其他：身份 / 属性类 ——
  { text: '买过网红爆款产品的人', category: '其他' },
  { text: '去过五个以上城市的人', category: '其他' },
  { text: '家里养过两只以上宠物的人', category: '其他' },
  { text: '穿42码以上鞋子的人', category: '其他' },
  { text: '穿过奇特图案衣服的人', category: '其他' },

  /* ============================================================
   * 以下为「X 的喝」风格，抄录自另两个转盘视频
   * （抖音「今天谁喝酒」、「1000个喝酒大转盘」）。
   * 符合条件的人就喝。分类：感情/习惯/饮食/外形/才艺/爱好/性格/互动
   * ============================================================ */

  // —— 感情 / 前任 ——
  { text: '放不下前任的喝', category: '感情' },
  { text: '被前任视奸过的喝', category: '感情' },
  { text: '还记得前任生日的喝', category: '感情' },
  { text: '给前任买过贴身衣物的喝', category: '感情' },
  { text: '手机相册还存着和前任合照的喝', category: '感情' },
  { text: '购物软件还留着前任收货地址的喝', category: '感情' },
  { text: '被断崖式分手过的喝', category: '感情' },
  { text: '分手后还会替前任说好话的喝', category: '感情' },
  { text: '分手后前任的朋友追求过你的喝', category: '感情' },
  { text: '为恋人删过身边异性好友的喝', category: '感情' },
  { text: '有过“分手后还能做朋友”经历的喝', category: '感情' },
  { text: '恋爱时长最久的喝', category: '感情' },
  { text: '单身的喝', category: '感情' },
  { text: '有对象的喝', category: '感情' },
  { text: '被欺骗过感情的喝', category: '感情' },
  { text: '遭受过冷暴力还自我反思的喝', category: '感情' },

  // —— 习惯 ——
  { text: '抖音收藏超过100条的喝', category: '习惯' },
  { text: '今日没化妆的喝', category: '习惯' },
  { text: '点奶茶咖啡都要无糖的喝', category: '习惯' },
  { text: '今天微信步数超过一万的喝', category: '习惯' },
  { text: '有洁癖的喝', category: '习惯' },
  { text: '喝饮品习惯咬吸管的喝', category: '习惯' },
  { text: '今日出门带了充电宝的喝', category: '习惯' },
  { text: '上厕所必带手机的喝', category: '习惯' },
  { text: '喜欢咬指甲的喝', category: '习惯' },
  { text: '平时爱刷短剧的喝', category: '习惯' },
  { text: '最近一周通宵熬过夜的喝', category: '习惯' },
  { text: '此刻正在回微信的喝', category: '习惯' },
  { text: '上班带饭的喝', category: '习惯' },
  { text: '现在桌上放着钥匙串的喝', category: '习惯' },
  { text: '上课或开会睡着过的喝', category: '习惯' },
  { text: '睡觉要抱玩偶的喝', category: '习惯' },
  { text: '收藏夹吃灰超过100条的喝', category: '习惯' },
  { text: '设了6个以上闹钟的喝', category: '习惯' },
  { text: '今天洗了头的喝', category: '习惯' },
  { text: '闹钟3个以上还起不来的喝', category: '习惯' },
  { text: '通勤超过1小时的喝', category: '习惯' },
  { text: '化妆要花30分钟以上的喝', category: '习惯' },
  { text: '消息免打扰群超过5个的喝', category: '习惯' },
  { text: '朋友圈三天可见的喝', category: '习惯' },
  { text: '微信置顶3人以上的喝', category: '习惯' },
  { text: '今天迟到的喝', category: '习惯' },

  // —— 饮食口味 ——
  { text: '吃火锅必点脑花的喝', category: '饮食' },
  { text: '不吃羊肉的喝', category: '饮食' },
  { text: '不吃葱姜蒜的喝', category: '饮食' },
  { text: '不吃香菜的喝', category: '饮食' },
  { text: '吃火锅只蘸麻酱的喝', category: '饮食' },
  { text: '不吃内脏的喝', category: '饮食' },
  { text: '能直接喝醋的喝', category: '饮食' },

  // —— 外形 / 属性 ——
  { text: '没打耳洞的喝', category: '外形' },
  { text: '有耳洞的喝', category: '外形' },
  { text: '单眼皮的喝', category: '外形' },
  { text: '头发染过色的喝', category: '外形' },
  { text: '头发没染过色的喝', category: '外形' },
  { text: '有纹身的喝', category: '外形' },
  { text: '身上戴着首饰的喝', category: '外形' },
  { text: '手上戴着戒指的喝', category: '外形' },
  { text: '鞋子码数最大的喝', category: '外形' },
  { text: '有腹肌或马甲线的喝', category: '外形' },
  { text: '种过睫毛的喝', category: '外形' },
  { text: '美甲贴钻的喝', category: '外形' },
  { text: '带了气垫或粉饼的喝', category: '外形' },
  { text: '有刘海的喝', category: '外形' },
  { text: '文过眉的喝', category: '外形' },
  { text: '涂了指甲油的喝', category: '外形' },
  { text: '穿白袜的喝', category: '外形' },
  { text: '穿洞洞鞋的喝', category: '外形' },
  { text: '穿运动鞋的喝', category: '外形' },
  { text: '穿牛仔裤的喝', category: '外形' },
  { text: '穿破洞裤的喝', category: '外形' },
  { text: '穿拖鞋的喝', category: '外形' },
  { text: '袜子有破洞的喝', category: '外形' },
  { text: '戴手表的喝', category: '外形' },
  { text: '戴眼镜的喝（隐形眼镜也算）', category: '外形' },
  { text: '是左撇子的喝', category: '外形' },
  { text: '体重过百的喝（不分性别）', category: '外形' },
  { text: '手机壳花里胡哨的喝', category: '外形' },
  { text: '用动漫头像的喝', category: '外形' },
  { text: '名字带“雨”“雪”“风”的喝', category: '外形' },
  { text: '名字是三个字的喝', category: '外形' },
  { text: '身份证尾号是单数的喝', category: '外形' },
  { text: 'A型血的喝', category: '外形' },
  { text: 'B型血的喝', category: '外形' },
  { text: 'AB型血的喝', category: '外形' },
  { text: '处女座的喝', category: '外形' },

  // —— 才艺 / 技能 ——
  { text: '会做饭的喝', category: '才艺' },
  { text: '不会做饭的喝', category: '才艺' },
  { text: '会游泳的喝', category: '才艺' },
  { text: '不会游泳的喝', category: '才艺' },
  { text: '会PS或剪视频的喝', category: '才艺' },
  { text: '用九宫格打字的喝', category: '才艺' },
  { text: '会玩滑板或轮滑的喝', category: '才艺' },
  { text: '会织毛衣或勾线的喝', category: '才艺' },
  { text: '会说方言的喝', category: '才艺' },
  { text: '会开车的喝（有驾照就算）', category: '才艺' },
  { text: '背不出圆周率后9位的喝', category: '才艺' },
  { text: '不会背《出师表》的喝', category: '才艺' },
  { text: '说不出三个歌名的喝', category: '才艺' },
  { text: '说不出父母生日的喝', category: '才艺' },

  // —— 爱好 / 娱乐 ——
  { text: '相信外星人的喝', category: '爱好' },
  { text: '相信星座或塔罗的喝', category: '爱好' },
  { text: '爱看恐怖片的喝', category: '爱好' },
  { text: '玩过王者荣耀的喝', category: '爱好' },
  { text: '王者荣耀上过星耀的喝', category: '爱好' },
  { text: '王者荣耀打到王者的喝', category: '爱好' },
  { text: '王者荣耀里有CP的喝', category: '爱好' },
  { text: '玩过摩尔庄园的喝', category: '爱好' },
  { text: '看过《甄嬛传》三遍以上的喝', category: '爱好' },
  { text: '追过星（买周边或打投）的喝', category: '爱好' },
  { text: '买过基金或股票的喝', category: '爱好' },
  { text: '买过盲盒的喝', category: '爱好' },
  { text: '有副业的喝（微商/摆摊/自媒体）', category: '爱好' },
  { text: '去过3个以上国家的喝', category: '爱好' },
  { text: '网购退货超过10次的喝', category: '爱好' },
  { text: '给差评过的喝', category: '爱好' },
  { text: '养猫的喝', category: '爱好' },

  // —— 性格 / 身体 ——
  { text: '有选择困难症的喝', category: '性格' },
  { text: '嘴巴毒爱吐槽的喝', category: '性格' },
  { text: '有鼻炎的喝', category: '性格' },
  { text: '爱抠痘痘的喝', category: '性格' },
  { text: '打呼噜的喝', category: '性格' },
  { text: '怕鬼的喝', category: '性格' },
  { text: '怕虫子的喝', category: '性格' },
  { text: '怕高的喝', category: '性格' },
  { text: '怕蟑螂的喝', category: '性格' },
  { text: '公认酒量最差的喝', category: '性格' },
  { text: '顺走过别人打火机的喝', category: '性格' },
  { text: '微信好友第八位是异性的喝', category: '性格' },
  { text: '发起的群聊自己最后一个进的喝', category: '性格' },

  // —— 互动 / 惩罚（需主持人或全场参与）——
  { text: '最晚到场的人喝', category: '互动' },
  { text: '找一个人猜拳，输的喝', category: '互动' },
  { text: '被指定为全场最骚的喝', category: '互动' },
  { text: '比主持人高的都得喝', category: '互动' },
  { text: '发个红包，手气最佳的喝', category: '互动' },
  { text: '一周内亲过人的喝（亲人宠物也算）', category: '互动' },
  { text: '做过饭的喝，做几次喝几口', category: '互动' },
  { text: '和你对上眼的喝', category: '互动' },
  { text: '玩三局游戏，中途看手机的喝', category: '互动' },
  { text: '故事接龙笑出声或接不下去的喝', category: '互动' },
  { text: '不敢当场删掉一个异性微信的喝', category: '互动' },
  { text: '被点到“最想吻的人”，拒答就喝一瓶', category: '互动' },
  { text: '被主持人指定为海王或海后的喝', category: '互动' },
];
